### ISSUE TITLE
Prevent loading of CloudSponge assets from loading on all pages if widget is not used.

### ISSUE THREAD

**Issue by BoweFrankema** [boonebgorges/invite-anyone#121]
Currently if you enable CloudSponge there is a ton of assets loaded on every page. 

    https://api.cloudsponge.com/address_books.js?ver=4.0.1
    https://api.cloudsponge.com/javascripts/address_books/floatbox.css
    https://api.cloudsponge.com/javascripts/address_books/graphics/blank.gif
    https://api.cloudsponge.com/javascripts/address_books/graphics/shadowBottom_s12_r12.png
    https://api.cloudsponge.com/javascripts/address_books/graphics/shadowCorner_s12_r0.png
    https://api.cloudsponge.com/javascripts/address_books/graphics/shadowCorner_s12_r12.png
    https://api.cloudsponge.com/javascripts/address_books/graphics/shadowLeft_s12_r12.png
    https://api.cloudsponge.com/javascripts/address_books/graphics/shadowRight_s12_r12.png
    https://api.cloudsponge.com/javascripts/address_books/graphics/shadowTop_s12_r12.png
    https://api.cloudsponge.com/javascripts/address_books/modules/core.js
    https://api.cloudsponge.com/javascripts/address_books/options.js

It would be nice if this could be solved by only loading the CloudFlare assets on the proper page (Group Invite and User Invite pages).

When the widget is used you could use * is_widget_active* (according to yourself!)

Here are the conditional you could use and seem to work:

    if ( bp_is_group() && bp_is_current_action( 'invite-anyone' ) || bp_is_user() && bp_is_current_action( 'invite-new-members' ) )

**Comment by boonebgorges** [comment]
Done. This will be in the next version.
