### ISSUE TITLE
PHP Warning with v1.3.6

### ISSUE THREAD

**Issue by schwarzaufweiss** [boonebgorges/invite-anyone#122]
I'm not using the widget but got the following with WP 3.9.3 and BP 2.0.3 …
PHP Warning: _() expects exactly 1 parameter, 2 given in /wp-content/plugins/invite-anyone/widgets/widgets.php on line 92

**Comment by boonebgorges** [comment]
Thanks, Hans! Little typo on my part. This will be fixed in the next 
release.
