### ISSUE TITLE
Typo in v1.3.6

### ISSUE THREAD

**Issue by schwarzaufweiss** [boonebgorges/invite-anyone#123]
In /lib/bbg-cpt-pag you have a typo on line 200: "invite-anyone" should be "bp-invite-anyone" (otherwise the string isn't localized)

**Comment by boonebgorges** [comment]
Thanks for pointing this out, @schwarzaufweiss. For better practice, `invite-anyone` should probably be used throughout (see http://ottopress.com/2013/language-packs-101-prepwork/).

**Comment by schwarzaufweiss** [comment]
Would say in by-email.php on line 694 the referring language file should be invite-anyone and not buddypress.
