### ISSUE TITLE
Replace deprecated like_escape with $wpdb->esc_like

### ISSUE THREAD

**Issue by danbrellis** [boonebgorges/invite-anyone#132]
Any easy fix in /group-invites/group-invites.php

In the function get_search_sql() a `global $wpdb;` needs to be added. And when building the `$searches` array on line 349, replace `like_escape` with `$wpdb->esc_like` per https://codex.wordpress.org/Function_Reference/like_escape recommendation.

**Comment by boonebgorges** [comment]
Thanks!
