### ISSUE TITLE
mask link

### ISSUE THREAD

**Issue by HDInfautre** [boonebgorges/invite-anyone#140]
Hi,
I had big problems with a complaint from users.
On a dating site, a woman had been invited by a man join the site.
Her husband caught it by putting the first name + name of his wife on the google search engine
This woman had never published anything on the internet.
It thus appeared the link on the results page that can make believe that the person is registered on the dating site:  www.XXX.eu/ia_invitees/leila-durand-rennes-fr/
Is what He would be possible not to natively enable indexing links ia by search engines

Regards

**Comment by boonebgorges** [comment]
@HDInfautre Thanks for the ticket. I'll look into it over the next few days and let you know what I find.

**Comment by boonebgorges** [comment]
Thanks for your patience as I looked into this. I've found the issue and it'll be corrected in the next version of Invite Anyone.
