### ISSUE TITLE
Settings page error - max_invites auto-reset to 1 invite at a time 

### ISSUE THREAD

**Issue by Jon007** [boonebgorges/invite-anyone#148]
Settings, Invite Anyone, 

- General Settings, "Number of email invitations users are permitted to send at a time" is fixed to 1.
- Access Control, "Limit per-user invitations" is fixed to 1

If you change the number and save, it looks like the save has taken effect, however if you then refresh the screen the number returns to 1...  and in the email invite screen, the limit of 1 is enforced...   for both fields..

Also reported by many people on the Wordpress.org support forums:
https://wordpress.org/support/topic/only-one-invitation-can-be-sent-at-a-time/

**Comment by Jon007** [comment]
The error is in admin-panel.php.
```
			case 'max_invites' :
			case 'days_since' :
			case 'limit_invites_per_user' :
				$value = intval( $input );
			break;

```

$input here is the entire array of values...  according to the intval conversion rules, Empty arrays return 0, non-empty arrays return 1, so this will always return 1....

**Comment by Jon007** [comment]
@boonebgorges on wordpress.org people are continuing to ask for this fix to be released, it's another one from the security fix a while back...

**Comment by corsacca** [comment]
@boonebgorges this issue is affecting me too.
